//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goldfish
{
    using System;
    using System.Collections.Generic;
    
    public partial class borcIslemleri
    {
        public int Id { get; set; }
        public string isim { get; set; }
        public string borcTuru { get; set; }
        public string islem { get; set; }
        public Nullable<double> tutar { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
