//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goldfish
{
    using System;
    using System.Collections.Generic;
    
    public partial class satislar
    {
        public int Id { get; set; }
        public string firma { get; set; }
        public string balikTuru { get; set; }
        public string balikCinsi { get; set; }
        public Nullable<double> adet { get; set; }
        public Nullable<double> birimFiyat { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<double> toplam { get; set; }
    }
}
