//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace goldfish
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string tur { get; set; }
        public string cins { get; set; }
        public Nullable<double> adet { get; set; }
        public Nullable<System.DateTime> alimTarihi { get; set; }
        public Nullable<double> alisFiyati { get; set; }
    }
}
